
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/keum
    username: keum
    password: keum

  redis:
    host: localhost
    port: 6379

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      mode: always
  #TODO : submodule 정의 (jwt 관련, DB 관련, Oauth 관련), AWS EC2 배포
jwt:
  secret-key: keum.2022.tlswornjs.dlatnwls.server.key.v0.01
  # 30 days
  access-token-expired-time-ms: 1800000
  refresh-token-expired-time-ms: 1296000000

logging:
  level:
    com.project.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
