spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${{ secrets.RDS_URL }}
    username: ${{ secrets.RDS_USERNAME }}
    password: ${{ secrets.RDS_PASSWORD }}

  redis:
    host: ${{ secrets.REDIS_HOST }}
    port: 6379

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 100
  sql:
    init:
      mode: always

logging:
  level:
    com.project.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

jwt:
  secret-key: ${{ secrets.SECRET_KEY }}
  # 30 days
  access-token-expired-time-ms: ${{ secrets.ACCESS_TOKEN_EXPIRED_TIME }}
  refresh-token-expired-time-ms: ${{ secrets.REFRESH_TOKEN_EXPIRED_TIME }}
