spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://balance-up.c9jptfgns397.ap-northeast-2.rds.amazonaws.com:5432/keum
    username: balanceup
    password: balanceup

  redis:
    host: localhost
    port: 6379

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      mode: always

  config:
    import: balnce-up-key/oauth.yml

logging:
  level:
    com.project.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
